version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: gradle
    directory: "/gradle/config"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
