###
### author: Ho Huu Ngoan (ngoanh2n@gmail.com)
###
version: 2.1

executors:
  executor_macos:
    macos:
      xcode: 13.4.1
    shell: /bin/bash
    resource_class: medium
  executor_linux:
    machine:
      image: ubuntu-2004:2022.07.1
    shell: /bin/bash
    resource_class: medium
  executor_windows:
    machine:
      image: windows-server-2022-gui:current
    shell: bash.exe
    resource_class: windows.medium
      
commands:
  cache_store:
    steps:
      - save_cache:
          name: Store Gradle cache
          paths:
            - ~/.gradle
          key: gradle-{{checksum "build.gradle"}}
  cache_restore:
    steps:
      - restore_cache:
          name: Restore Gradle cache
          key: gradle-{{checksum "build.gradle"}}
  test_execute:
    steps:
      - run:
          name: Execute the test
          command: |
            chmod +x gradlew
            ./gradlew clean test
          when: always

jobs:
  build_and_test:
    parameters:
      os: { type: executor }
    executor: <<parameters.os>>
    steps:
      - cache_restore
      - test_execute
      - cache_store

workflows:
  test_execution:
    jobs:
      - build_and_test:
          name: <<matrix.os>>
          filters:
            branches:
              only: master
          matrix:
            parameters:
              os:
                - executor_macos
                - executor_linux
                - executor_windows
