###
### Author: ngoanh2n
### https://docs.github.com/en/actions
### https://github.com/marketplace?type=actions
###
name: Build
on:
  pull_request:
    types: [ opened, review_requested ]
  workflow_dispatch:
jobs:
  test:
    name: ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Build
        run: ./gradlew clean build
      - name: Summarize JUnit report
        if: success() || failure()
        uses: mikepenz/action-junit-report@v4
        with:
          check_name: report_ubuntu
          report_paths: build/reports/test/TEST-*.xml
