###
### Author: ngoanh2n
### https://docs.github.com/en/actions
### https://github.com/marketplace?type=actions
###
name: Test
on:
  push:
    branches: [develop]
  pull_request:
    types: [opened, review_requested]
jobs:
  test:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        java_version: [17]
    name: ${{ matrix.os }}_java${{ matrix.java_version }}
    runs-on: ${{ matrix.os }}
    env:
      MATRIX_JOB_NAME: ${{ matrix.os }}_java${{ matrix.java_version }}
    steps:
      - name: "[Prepare] Checkout"
        uses: actions/checkout@v4
      - name: "[Prepare] Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java_version }}
      - name: "[Test] Execute"
        run: ./gradlew clean test
      - if: success() || failure()
        name: "[Report] JUnit report"
        uses: mikepenz/action-junit-report@v4
        with:
          check_name: JUnit ${{ env.MATRIX_JOB_NAME }}
          report_paths: build/reports/test/TEST-*.xml
